web-app01/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :product

   root 'welcome#index'

     resources :wows do
       member do
         get 'wowstart'
         post 'wowend'
       end
  
       collection do
         get 'search'
         get 'search2'
       end
     end

     resources :wows2 do
       member do
         get 'wow2get'
         post 'wow2post'
       end
  
       collection do
         get 'wow2collget'
       end
     end     

end

web-app01/app/models/post.rb
class Post < ActiveRecord::Base
end

web-app01/app/models/product.rb
class Product < ActiveRecord::Base
end

web-app01/app/models/search/base.rb
class Search::Base
  include ActiveModel::Model
  include ActiveModel::Validations::Callbacks

  def contains(arel_attribute, value)
    arel_attribute.matches("%#{escape_like(value)}%")
  end

  def escape_like(string)
    string.gsub(/[\\%_]/) { |m| "\\#{m}" }
  end

  def value_to_boolean(value)
    ActiveRecord::ConnectionAdapters::Column.value_to_boolean(value)
  end
end

web-app01/app/models/search/product.rb
class Search::Product < Search::Base
  ATTRIBUTES = %i(
    code
    name name_kana
    price_from price_to
    purchase_cost_from purchase_cost_to
    availability
  )
  attr_accessor(*ATTRIBUTES)

  def matches
    t = ::Product.arel_table
    results = ::Product.all
    results = results.where(contains(t[:code], code)) if code.present?
    results = results.where(contains(t[:name], name)) if name.present?
    results = results.where(contains(t[:name_kana], name_kana)) if name_kana.present?
    results = results.where(t[:price].gteq(price_from)) if price_from.present?
    results = results.where(t[:price].lteq(price_to)) if price_to.present?
    if purchase_cost_from.present?
      results = results.where(t[:purchase_cost].gteq(purchase_cost_from))
    end
    if purchase_cost_to.present?
      results = results.where(t[:purchase_cost].lteq(purchase_cost_to))
    end
    results = results.where(availability: true) if value_to_boolean(availability)
    results
  end
end

web-app01/app/models/wow.rb
class Wow < ActiveRecord::Base
end

web-app01/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    # GET /posts/new
  def new 
  end
    # POST /posts
  def create
       # render text: params[:post].inspect
       @post = Post.new(post_params)
       @post.save
       redirect_to @post
  end
    # GET /post/:id
  def show
      @post = Post.find(params[:id])
  end
  # GET /posts
  def index
      @posts = Post.all
  end
  private
  def post_params
    #params.require(:post).permit(:title, :text)
    params.require(:post).permit(:title, :text)
  end
end

web-app01/app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @product = Search::Product.new
  end
  def search
    @product = Search::Product.new(search_params)
    @products = @product
      .matches
      .order(availability: :desc, code: :asc)
      .decorate
  end

  private

  # 検索フォームから受け取ったパラメータ
  def search_params
    params
      .require(:search_product)
      .permit(Search::Product::ATTRIBUTES)
  end
end

web-app01/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

web-app01/app/controllers/wows2_controller.rb
class Wows2Controller < ApplicationController
  def index
  end

  def wow2get
  end

  def wow2collget
  end
end

web-app01/app/controllers/wows_controller.rb
class WowsController < ApplicationController
  def index
    @form = Wow.new(params.require(:wow))
  end
  def find
    @form = Wow.new
  end
end

web-app01/app/helpers/posts_helper.rb
module PostsHelper
end

web-app01/app/helpers/product_helper.rb
module ProductHelper
end

web-app01/app/helpers/welcome_helper.rb
module WelcomeHelper
end

web-app01/app/helpers/wows2_helper.rb
module Wows2Helper
end

web-app01/app/helpers/wows_helper.rb
module WowsHelper
end

web-app01/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebApp01</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

web-app01/app/views/posts/index.html.erb
<h1>全ての投稿一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
    </tr>
  <% end %>
</table>
<%= link_to "私のブログ", controller: "posts" %>
<%= link_to '新しい投稿', new_post_path %>
<%= link_to "wows", controller: "wows" %>

<%= link_to '戻る', posts_path %>

web-app01/app/views/posts/new.html.erb
<h1>新しい投稿</h1>
<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text, "内容" %><br>
    <%= f.text_area :text, cols: 60, rows: 8 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to '戻る', posts_path %>

web-app01/app/views/posts/show.html.erb
<p>
  <strong>タイトル：</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>内容：</strong>
  <%= @post.text %>
</p>

<%= link_to "私のブログ", controller: "posts" %>
<%= link_to '戻る', posts_path %>

web-app01/app/views/product/index.html.erb
<h1>products_index</h1>
<%= form_for :product, url: products_path do |f| %>
<!-- form_for(@product, url: search_products_path, html: { method: :get, class: 'form-horizontal', role: 'form' }) do |f| %>
-->
  <%= f.label :code, "code" %><br>
  <%= f.text_field :code %>
  <%= f.label :name, "name" %><br>  
  <%= f.text_field :name %>
<% end %>

web-app01/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<h1>Hello World</h1>
<h1>Hello, Rails!</h1>
<%= link_to "私のブログ", controller: "posts" %>
<%= link_to 'myself',  controller: "product" %>
<%= link_to '新しい投稿', new_post_path %>
<%= link_to "wows", controller: "wows" %>

web-app01/app/views/wows/index.html.erb
<h1>Wows#index</h1>
<p>Find me in app/views/wows/index.html.erb</p>

<%= form_for @form, url: '/employees', method: :get do |f| %>
  <p>
    <%= f.label :name, '氏名:' %>
    <%= f.text_field :name %>
  </p>
 <p>
    <%= submit_tag '検索する' %>
  </p>
<% end %>

web-app01/app/views/wows/luck.html.erb
<h1>Wows#search</h1>
<p>Find me in app/views/wows/search.html.erb</p>

web-app01/app/views/wows/search.html.erb
<h1>Wows#search</h1>
<p>Find me in app/views/wows/search.html.erb</p>
<%= form_tag({action: :index}, {method: :get}) do %>
  <p>
    <%= label_tag :name, '氏名:' %>
    <%= text_field_tag :name, @name %>
  </p>
  <p>
    <%= submit_tag '検索する' %>
  </p>
<% end %>

web-app01/app/views/wows/search2.html.erb
<h1>Wows#search</h1>
<p>Find me in app/views/wows/search.html.erb</p>

web-app01/app/views/wows/wowstart.html.erb
<h1>Wows#wowstart</h1>
<p>Find me in app/views/wows/wowstart.html.erb</p>

web-app01/app/views/wows2/index.html.erb
<h1>Wows2#index</h1>
<p>Find me in app/views/wows2/index.html.erb</p>

web-app01/app/views/wows2/wow2collget.html.erb
<h1>Wows2#wow2collget</h1>
<p>Find me in app/views/wows2/wow2collget.html.erb</p>

web-app01/app/views/wows2/wow2get.html.erb
<h1>Wows2#wow2get</h1>
<p>Find me in app/views/wows2/wow2get.html.erb</p>